arb-dir: lib/l10n
output-dir: lib/l10n/generated
untranslated-messages-file: lib/l10n/missing_localizations.json
template-arb-file: proxo_en.arb
output-localization-file: proxo_localizations.dart
output-class: ProxoLocalizations
preferred-supported-locales: "en"
synthetic-package: false
use-deferred-loading: false
