name: proxo
description: A simple tic-tac-toe game, yet developed as a corporate app.
version: 0.5.10+41

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.9.2
  lottie: ^1.2.2
  flutter_svg: ^1.0.3
  auto_size_text: ^3.0.0
  package_info_plus: ^1.4.0
  loading_animations: ^2.2.0
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  injectable: ^1.5.3
  get_it: ^7.2.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  hive_generator: ^1.1.2
  injectable_generator: ^1.5.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/proxo_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/logo/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
